name: building artifact using maven

on : push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: checking maven version
    run: |
      mvn --version  
  - name: cloning git repo
      git clone https://github.com/praveendevops1337/MY_GITHUB_ACTIONS.git
  - name: checking git location
    run: |
      pwd  
