name: building artifact using maven

on : push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: checking maven version
    run: |
      mvn --version
  - name: building artifact using maven
    run: |
      mvn clean package -f MY_GITHUB_ACTIONS/simple/pom.xml 
  - name: checking mvn artifact path
    run: |
       pwd
