name: clarifying doubuts

on : push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: checking docker version
    run: |
      docker --version
  - name: checking java version
    run: |
      java -version
  - name: checking mavan version
    run: |   
      mvn --version
  - name: present working directory
    run: |   
      pwd
  - name: checking git --version
    run: |
      git --version
      
      
      
